máquina = {
    "Grudante":["incomum"],
    "Combustível":["comum"],
    "Atadura":["comum"],
    "Kit Médico":["incomum"],
    "Poção de escudo pequena":["incomum"],
    "maçã":["incomum"],
    "Granada de Onda de Choque":["épica"],
    "Cogumelo":["incomum"],
    "Alface":["comum"],
    "Vara de pesca":["comum"],
    "Cura-Cura":["rara"],
    "Espingarda guardião do portão": ["comum","incomum","rara","épica","lendária"],
    "SMG Arauto": ["comum","incomum","rara","épica","lendária"],
    "Rifle A.E caçada lunar": ["comum","incomum","rara","épica","lendária"], 
    "Rifle de Assalto Belicoforjado": ["comum","incomum","rara","épica","lendária"], 
    "Escopeta Martelo": ["comum","incomum","rara","épica","lendária"],
    "Espingarda Automática Frenética": ["comum","incomum","rara","épica","lendária"], 
    "RA Nêmesis": ["comum","incomum","rara","épica","lendária"],
    "SMG Rajada de Trovão": ["comum","incomum","rara","épica","lendária"],
    "Rifle de Precisão do Ceifador": ["comum","incomum","rara","épica","lendária"],
    "Pistola Sentinela": ["comum","incomum","rara","épica","lendária"],
    "Canhão de Mão": ["comum","incomum","rara","épica","lendária"]
}